BotDetection::BotUserAgents = [
  "FacebookExternalHit/1.1",
  "FacebookExternalHit/1.0",
  "facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)",
  "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)",
  "facebookplatform/1.0 (+http://developers.facebook.com)",
  "Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)",
  "Mozilla/5.0 (compatible; SISTRIX Crawler; http://crawler.sistrix.net/)",
  "ShowyouBot (http://showyou.com/crawler)",
  "Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ahrefs.com/robot/)",
  "Mozilla/5.0 (compatible; proximic; +http://www.proximic.com/info/spider.php)",
  "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-GB; rv:1.0; trendictionbot0.5.0; trendiction search; http://www.trendiction.de/bot; please let us know of any problems; web at trendiction.com) Gecko/20071127 Firefox/3.0.0.11",
  "ia_archiver (+http://www.alexa.com/site/help/webmasters; crawler@alexa.com)",
  "Mozilla/5.0 (compatible; Exabot/3.0 (BiggerBetter); +http://www.exabot.com/go/robot)",
  "Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/2.0; +http://go.mail.ru/help/robots)",
  "Mozilla/5.0 (compatible; SMTBot/1.0; +http://www.similartech.com/smtbot)",
  "Twitterbot/1.0",
  "LinkedInBot/1.0 (compatible; Mozilla/5.0; Jakarta Commons-HttpClient/3.1 +http://www.linkedin.com)",
  "Mozilla/5.0 (compatible; XoviBot/2.0; +http://www.xovibot.net/)",
  "Mozilla/5.0 (compatible; SearchmetricsBot; http://www.searchmetrics.com/en/searchmetrics-bot/)",
  "Pinterest/0.1 +http://pinterest.com/",
  "Googlebot (gocrawl v0.4)",
  "Mozilla/5.0 (compatible; Alexabot/1.0; +http://www.alexa.com/help/certifyscan; certifyscan@alexa.com)",
  "Flamingo_SearchEngine (+http://www.flamingosearch.com/bot)", # perhaps a search engine?
]