BotDetection::SearchEngineUserAgents = [
  "Baiduspider+(+http://www.baidu.com/search/spider.htm)",
  "Baiduspider+(+http://www.baidu.com/search/spider_jp.html)",
  "BaiDuSpider",
  "DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)",
  "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexImages/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexVideo/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexMedia/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexBlogs/0.99; robot; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexFavicons/1.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexWebmaster/2.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexPagechecker/1.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexImageResizer/2.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexDirect/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexDirect/2.0; Dyatel; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexNews/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexCatalog/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexAntivirus/2.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexZakladki/3.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; YandexMarket/1.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
  "Mozilla/5.0 (compatible; Yahoo Slurp;   http://help.yahoo.com/help/us/ysearch/slurp)",
  "Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html)",
  "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)",
  "Mozilla/5.0 (compatible; bingbot/2.0 +http://www.bing.com/bingbot.htm)",
  "msnbot/2.1",
  "msnbot/2.0b",
  "msnbot/1.1 (+http://search.msn.com/msnbot.htm)",
  "msnbot/1.1",
  "msnbot/1.0 (+http://search.msn.com/msnbot.htm)",
  "msnbot/0.9 (+http://search.msn.com/msnbot.htm)",
  "msnbot/0.11 ( http://search.msn.com/msnbot.htm)",
  "MSNBOT/0.1 (http://search.msn.com/msnbot.htm)",
]